### PR TITLE
cleaned up errors and fixed loading json

### PR DESCRIPTION
**Pull request by Kaceyr**
Not sure about the color change that I made, but the rest will fix some of the errors, as well as fixes the issue with the coverage.json not being loaded correctly.

### CODE REVIEW

**Comment by philipgiuliani** [comment]
Thanks a lot for the PR, is this huge `package.json` really required? No package has it.. :)

I will test this today and check why you have set the color to #fff. It should be better to use one of atoms variables, so that its theme-independent.

**Comment by Kaceyr** [comment]
When I get home tonight I will take a look at that package.json, I must have somehow added junk to that file.

**Comment by Kaceyr** [comment]
Removed the junk in the package file.

**Comment by philipgiuliani** [comment]
Thanks a lot, would be great if you could also change the class `.atom-workspace` to a element selector `atom-workspace`

**Comment by Kaceyr** [comment]
Changed that back and removed the color css

**Comment by philipgiuliani** [comment]
Perfect i'll test it tomorrow morning!

**Comment by philipgiuliani** [comment]
I released a new version :)

**Pull request merged**
